apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: monitoring
spec:
  selector:
    app: monitoring-platform
  type: NodePort
  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


# echo Hello World in fisierul txt - job 1 
# cat  - > Hello World
# append Bye Bye world in acelasi fisier txt- job 2
# cat 